import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import ProductProvider from "@/components/ProductProvider";
import { ToastContainer, toast } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

export const metadata: Metadata = {
  title: "Crud next app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ProductProvider>
          <ToastContainer />
          {children}
        </ProductProvider>
      </body>
    </html>
  );
}
